.\" pluck-comics.1
.TH PLUCK-COMICS 1 "Plucker 1.1 - http://plkr.org/"
.SH NAME
pluck-comics \- gathers selected comics for Plucker
.SH SYNOPSIS
\fBpluck-comics\fR
[-a] [-d] [-h] [-i] [-l \fIlocation\fR] comic ...
.SH DESCRIPTION
.B pluck-comics
gathers comics from selected websites for Plucker. Run the tool with no options to get a list of all available comics.
.SH OPTIONS
.TP
\fB-a\fR
collect all known comics
.TP
\fB-d\fR
Delete \fBall\fR files in \fIlocation\fR before gathering new ones
.TP
\fB-h\fR
create a home page in \fIlocation\fR for the comics
.TP
\fB-i\fR
put icons on home page
.TP
\fB-l\fR \fIlocation\fR
the location to store the comics
.SH "AUTHOR"
Christopher R. Hawks <chrish@syscon-intl.com>  (man page by Michael Nordstrom, <micke@sslug.dk>)

Report bugs to http://bugs.plkr.org or <plucker-bugs@rubberchicken.org>

